# docker-compose.yml
version: "3.8"

services:
  # 1. Redis: The Queue System
  redis:
    image: redis:alpine
    container_name: vercel_redis
    ports:
      - "6379:6379"

  # 2. MinIO: Local AWS S3 Replacement
  minio:
    image: minio/minio
    container_name: vercel_minio
    ports:
      - "9000:9000" # API Port (Code talks to this)
      - "9001:9001" # Console Port (You visit this in browser)
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
